{{- if not (lookup "rbac.authorization.k8s.io/v1" .Values.clusterRole.type .Values.namespace .Values.clusterRole.name ) }}
kind: {{ .Values.clusterRole.type }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.clusterRole.name }}
  annotations:
    helm.sh/resource-policy: keep
  namespace: {{ .Values.namespace }}
rules:
  - verbs:
      - get
      - list
      - update
      - create
      - patch
    apiGroups:
      - '*'
    resources:
      - jobs
{{- end }}