{{- if not (lookup "rbac.authorization.k8s.io/v1" .Values.clusterRoleBinding.type .Values.namespace .Values.clusterRoleBinding.clusterRoleBindingName ) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.clusterRoleBinding.type }}
metadata:
  name: {{ .Values.clusterRoleBinding.clusterRoleBindingName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: {{ .Values.clusterRole.type }}
  name: {{ .Values.clusterRole.clusterRoleName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}