{{- if not (lookup "rbac.authorization.k8s.io/v1" .Values.clusterRoleBinding.type .Values.namespace .Values.clusterRoleBinding.name ) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.clusterRoleBinding.type }}
metadata:
  name: {{ .Values.clusterRoleBinding.name }}
  annotations:
    helm.sh/resource-policy: keep
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: {{ .Values.clusterRole.type }}
  name: {{ .Values.clusterRole.name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}