{{- if not (lookup "rbac.authorization.k8s.io/v1" .Values.clusterRole.type .Values.namespace .Values.clusterRole.clusterRoleName ) }}
kind: {{ .Values.clusterRole.type }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.clusterRole.clusterRoleName }}
  annotations:
    "helm.sh/hook": "pre-install"
rules:
  - verbs:
      - get
      - list
      - update
      - create
      - patch
    apiGroups:
      - '*'
    resources:
      - jobs
{{- end }}
