apiVersion: v1.edp.epam.com/v1alpha1
kind: KeycloakClient
metadata:
  name: {{ .Values.keycloakClient.clientName }}
spec:
  clientId: {{ .Values.keycloakClient.clientId }}
  description: "Role for history-excerptor-chart service"
  public: false
  serviceAccount:
    enabled: true
  secret: {{ .Values.keycloakClient.secretName }}
  directAccess: false
  audRequired: false
  targetRealm: {{ .Values.namespace }}-{{ .Values.keycloakClient.realm }}