{{- if not (lookup "v1" "Secret" .Values.namespace .Values.keycloakClient.secretName ) }}
{{- $secret := (lookup "v1" "Secret" .Values.namespace .Values.keycloakClient.secretName ) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloakClient.secretName }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
  {{- if $secret }}
data:
  clientSecret: {{ $secret.data.clientSecret }}
  {{- else }}
stringData:
  {{- $clientSecret := uuidv4 | quote }}
  clientSecret: {{ $clientSecret }}
{{- end }}
{{- end }}