{{- if not (lookup "v1" "ServiceAccount" .Values.namespace "history-excerptor") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  annotations:
    helm.sh/resource-policy: keep
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "history-excerptor-chart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}